# Generated by Django 4.0.1 on 2024-03-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_sizevariant_rename_size_name_size_size_and_more'),
        ('accounts', '0003_remove_cartitems_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sizevariant'),
        ),
    ]
