# Generated by Django 4.0.1 on 2024-03-09 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_size_variant_product_size_variant'),
        ('accounts', '0004_cartitems_size_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sizevariant'),
        ),
    ]
