# Generated by Django 4.0.1 on 2024-04-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_productcustomization_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomization',
            name='product_name',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
