# Generated by Django 4.0.1 on 2024-04-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_cartitems_size_variant_cartitems_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
