# Generated by Django 4.0.1 on 2024-04-05 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_product_quantity_remove_product_size'),
        ('accounts', '0019_remove_cartitems_quantity_remove_cartitems_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='size_variant',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quantity'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size'),
        ),
    ]
