# Generated by Django 4.0.1 on 2024-04-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_quantity_quantity_alter_size_size'),
        ('accounts', '0021_alter_cartitems_quantity_alter_cartitems_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quantity'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size'),
        ),
    ]
