# Generated by Django 4.0.1 on 2024-04-06 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_remove_quantity_quantity_remove_size_size'),
        ('accounts', '0023_remove_cartitems_quantity_remove_cartitems_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_quantity', to='products.variant'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_size', to='products.variant'),
        ),
    ]
