# Generated by Django 4.0.1 on 2024-04-06 05:11

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_cartitems_quantity_alter_cartitems_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name=products.models.Quantity),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=products.models.Size),
        ),
    ]
