# Generated by Django 4.0.1 on 2024-04-06 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_remove_size_quantity_quantity_quantity_and_more'),
        ('accounts', '0026_alter_cartitems_quantity_alter_cartitems_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_quantity', to='products.quantity'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_size', to='products.size'),
        ),
    ]
