# Generated by Django 4.0.1 on 2024-04-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_cartitems_quantity_alter_cartitems_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomization',
            name='quantity',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='size',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productcustomization',
            name='feeding_type',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productcustomization',
            name='sleeve_type',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productcustomization',
            name='zip_type',
            field=models.TextField(max_length=50),
        ),
    ]
