# Generated by Django 4.0.1 on 2024-04-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_cartitems_quantity_remove_cartitems_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='size_name',
            new_name='size',
        ),
    ]
