# Generated by Django 4.0.1 on 2024-04-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_rename_size_name_variant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
