# Generated by Django 4.0.1 on 2024-04-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_variant_quantity_alter_variant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.AddField(
            model_name='variant',
            name='quantities',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='sizes',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
