# Generated by Django 4.0.1 on 2024-04-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_remove_variant_quantity_remove_variant_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='quantities',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='sizes',
            new_name='size',
        ),
    ]
