# Generated by Django 4.0.1 on 2024-03-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_sub',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
