# Generated by Django 4.0.1 on 2024-03-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_category_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_sub',
        ),
    ]
