# Generated by Django 4.0.1 on 2024-03-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_category_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dummy_price',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
