# Generated by Django 4.0.1 on 2024-03-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_dummy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dummy_price',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
