# Generated by Django 4.0.1 on 2024-03-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_dummy_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dummy_price',
            new_name='fake_price',
        ),
    ]
