# Generated by Django 4.0.1 on 2024-03-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_dummy_price_product_fake_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fake_price',
            new_name='dummy_price',
        ),
    ]
