# Generated by Django 4.0.1 on 2024-03-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_color_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ColorVariant',
        ),
    ]
