# Generated by Django 4.0.1 on 2024-03-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_quantityvariant_product_quantity_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_variant',
        ),
        migrations.DeleteModel(
            name='QuantityVariant',
        ),
    ]
