# Generated by Django 4.0.1 on 2024-03-09 05:34

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_quantity_variant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeVariant',
            new_name='Size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name=products.models.Size),
        ),
    ]
