# Generated by Django 4.0.1 on 2024-03-09 06:45

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_sizevariant_rename_size_name_size_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='size_variant',
            field=models.CharField(blank=True, max_length=100, verbose_name=products.models.SizeVariant),
        ),
    ]
