# Generated by Django 4.0.1 on 2024-03-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
