# Generated by Django 4.0.1 on 2024-03-26 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sleeve_type', models.CharField(max_length=100)),
                ('nighty_length', models.IntegerField()),
                ('feeding_type', models.CharField(max_length=100)),
                ('zip_option', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
