# Generated by Django 4.0.1 on 2024-03-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_customization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customization',
            old_name='zip_option',
            new_name='zip_type',
        ),
    ]
