# Generated by Django 4.0.1 on 2024-03-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_rename_zip_option_customization_zip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nighty_length', models.IntegerField()),
                ('sleeve_type', models.CharField(max_length=100)),
                ('feeding_type', models.CharField(max_length=100)),
                ('zip_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Customization',
        ),
    ]
