# Generated by Django 4.0.1 on 2024-04-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_productcustomization_feeding_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCustomization',
        ),
    ]
