# Generated by Django 4.0.1 on 2024-04-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_delete_productcustomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.TextField(max_length=100),
        ),
    ]
