# Generated by Django 4.0.1 on 2024-04-04 11:08

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_quantity_quantity_alter_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.TextField(blank=True, verbose_name=products.models.Quantity),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, max_length=100, verbose_name=products.models.Size),
        ),
    ]
