# Generated by Django 4.0.1 on 2024-04-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_quantity_quantity_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
