# Generated by Django 4.0.1 on 2024-04-06 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_quantity_quantity_alter_size_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.TextField(blank=True, max_length=100)),
                ('quantity', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
