# Generated by Django 4.0.1 on 2024-04-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='size',
            name='size',
        ),
    ]
