# Generated by Django 4.0.1 on 2024-04-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_cartitems_quantity_alter_cartitems_size'),
        ('products', '0044_remove_quantity_quantity_remove_size_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.AddField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
