# Generated by Django 4.0.1 on 2024-04-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_delete_variant_quantity_quantity_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
