# Generated by Django 4.0.1 on 2024-04-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_size_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='quantity',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
