# Generated by Django 4.0.1 on 2024-04-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_alter_size_quantity_alter_size_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='quantity',
        ),
    ]
