# Generated by Django 4.0.1 on 2024-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_remove_quantity_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='quantity',
        ),
        migrations.AddField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
