# Generated by Django 4.0.1 on 2024-04-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_alter_variant_quantity_alter_variant_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.AddField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
