# Generated by Django 4.0.1 on 2024-04-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_delete_variant_quantity_quantity_size_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='size',
            name='size',
        ),
    ]
